### ISSUE TITLE
Tag needed for SPM support.

### ISSUE THREAD

**Issue by skogland** [dapperstout/swift-bytes#5]
We need a new release tag for this package to be used as a transitive dependency. Xcode will stop you from using including a package if the package has SPM dependencies pointing to a branch instead of using a version tag. A 0.8.0 release would be greatly appreciated.

**Comment by dapperstout** [comment]
No problem, 0.8.0 is released.

**Comment by svdo** [comment]
@dapperstout I think you didn't yet publish to CocoaPods trunk yet, did you? I can probably do it if you like.

**Comment by dapperstout** [comment]
Right, I didn't. If you could do that then that would be great @svdo!

**Comment by svdo** [comment]
Done!
